### ISSUE TITLE
Using probot to act upon a repo without an event trigger

### ISSUE THREAD

**Issue by elliotblackburn** [probot/friction#10]
Probot currently functions really well for reacting to web hooks and taking some particular action, however there doesn't seem to be a concrete way of pushing data in the opposite direction (to probot and then to github, perhaps from some API route or something).

## Use case

A user may have a probot instance setup for their organisation which may do things like PR / Issue template enforcement. They may also want to log unhandled exceptions as a github issue as soon as they are raised in the system. Right now it seems the easiest way to get this working is to ignore probot and create a new service for this. Installation ID's make it difficult to make use of the GitHub Apps for small use cases (rather than market place based products), if probot could provide some pattern for this then that would be excellent!

It would be great for probot to be an all encompassing github bot framework, rather than just a github webhook framework.

**Comment by jbjonesjr** [comment]
I've done some noodling around setting probot up to listen to other "webhooks" (webhooks are really just a rest call into probot) from sources other than GitHub. something like `probot.hook.register()` would create a new route for the rest/hook endpoint, register some events/actions that can be received, and would take in a mapping function to take the payload and return the proper context params.

This may require some sort of webhook namespacing (because events like `deployments` could be thrown from many different systems.

**Comment by elliotblackburn** [comment]
@jbjonesjr that sounds interesting, it'd be good to see some code samples to see the patterns you've used.

Just for clarification this issue was originally is less about webhooks and more about github apps API interaction. That said that's really useful information to know and would be good to keep track of!

**Comment by elliotblackburn** [comment]
I've unfortunately not had the time to pay with hubot much recently, however by the lack of connected PR's / issues I expect this is still relevant. If it's no longer relevant then please feel free to close it!
