### ISSUE TITLE
Improve documentation around using Probot Apps as plugins

### ISSUE THREAD

**Issue by JasonEtco** [probot/friction#13]
I was asked some questions around adding `probot-stale` to an existing Probot App, which I hadn't thought about. Thankfully, `@bkeepers` has! Adding the following to your `package.json` will call `.load()` on the plugin:

```json
"probot": {
  "apps": ["probot-stale"]
}
```

Unfortunately, this isn't well documented. With the recent changes we've made to loading plugins and auto-loading, improving this documentation would be a really useful change.

cc @joenash / @KaiFish who had the questions 💖

**Comment by hiimbex** [comment]
It's pretty well documented here: https://probot.github.io/docs/deployment/#combining-apps I thought. How do you think we could make that more visible?

**Comment by JasonEtco** [comment]
Oh @hiimbex didn't see that; in that case, it shouldn't be listed in the **Deployment** category. How about a new section under **Advanced** called **Combing Apps**?

**Comment by hiimbex** [comment]
Really? I thought it kinda made sense under deployment, since it's sort of telling the app to run in another environment. For example [welcome](https://github.com/behaviorbot/welcome) uses [3 apps combined](https://github.com/behaviorbot/welcome/blob/master/package.json) for the purpose of having one deployed app that does all the "welcoming".

But that page of docs is getting pretty long, so I'd be fine with breaking it up into a few more manageable individual pages, such as having deployment platforms (ie Now, Heroku, Glitch) in one section and separating combining apps and sentry into like an **Advanced Deployment** section?

**Comment by KaiFish** [comment]
I actually found that combining apps page this morning, and people were immediately confused with it being under deployment - they thought it was equivalent to running multiple probots all doing different things, rather than one probot doing all the needed tasks

**Comment by JasonEtco** [comment]
I see it as something totally different; to me, deployment is like "you're done your app, now what". Pulling in other apps feels more like building the thing, like `require()`ing modules.

**Comment by joenash** [comment]
From the perspective of a new user who was confronted with the deploy doc this morning, I do agree with Jason

**Comment by tcbyrd** [comment]
@JasonEtco Just trying to clean up a bit. Do you think there's more to do here is should we close it? (no i'm not 🤖 Stale, just trying to do some cleanup before it runs).

**Comment by JasonEtco** [comment]
> no i'm not 🤖 Stale

😂 

I'll go ahead and close this - I think we've resolved this path for Probot devs, since its been a while since we've had questions around it. Feel free to reopen if this pops up as a question again.

**Comment by itaditya** [comment]
@JasonEtco I have been following probot for 2 months, and up till now I didn't knew we can combine apps.  According to me, this feature should be highlighted a little more.
