### ISSUE TITLE
Confusing "Not Found" error for creating a new installation token

### ISSUE THREAD

**Issue by bkeepers** [probot/friction#16]
At least 3 users have reported this issue now. Here's the most [recent discussion](https://probot-talk.slack.com/archives/C6S4FC8AF/p1508817240000067):

> I'm getting an error that haven't had before, trying to figure out what's going on. It doesn't seem to be related to a code change since I wasn't getting these before...

```
03:50:29.530Z ERROR Probot: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/apps/#create-a-new-installation-token"}
  err: {
    "code": 404,
    "status": "Not Found",
    "message": "{\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/apps/#create-a-new-installation-token\"}"
  }
  --
  event: {
    "id": "79e16f20-b86e-11e7-8b0e-fc84f6028c53",
    "event": "pull_request",
    "action": "edited",
    "repository": "rtsao/probot-playground"
  }
```

> Any clues what this could be? I am testing my probot apps in a new github app. The webhook key and private key are correct...

This error is caused by having multiple GitHub Apps installed that are both pointing to the same URL, which is common in development with the way we currently setup localtunnel.

Suggestions:

1. Update the [Development docs](https://probot.github.io/docs/development/#configure-a-github-app) to strongly recommend using a single app for local development. Personally, I have an app called `bkeepers-dev` that has all permissions and webhooks enabled, and I just symlink `.env` and `private_key.pem` into the local directory.
1. Rescue this specific error and link to documentation that spells out this specific issue
1. Consider updating the default localtunnel config to include the app name in the URL (conflicts with the first recommendation, but might make sense as a default)

cc @rtsao @JasonEtco

**Comment by JasonEtco** [comment]
Thanks for putting this in an issue @bkeepers 👍

Similar to suggestion number **3**, there's this: https://github.com/probot/probot/issues/280 (discussion on changing the subdomain to different things, where the app name was suggested)

**Comment by dmleong** [comment]
I ran into this issue today after trying to do multiple probot installs using [create-probot-app](https://probot.github.io/docs/development/) and then trying to [simulate a webhook delivery](https://probot.github.io/docs/simulating-webhooks/) using `probot receive`. 

If you are using `probot receive` and have tried installing multiple apps on your account, the fixtures in the template repos won't work because the install ids are incorrect when going through the `create-probot-app` flow multiple times.

@JasonEtco and I fixed this by replacing the fixture template file contents (`test/fixtures/issues.labeled.json` or similar) with a fresh payload dump from the app's settings page 

![app settings page](https://user-images.githubusercontent.com/173/28491924-e03e91f2-6ebe-11e7-9570-6d48da68c6ca.png)

Hope this helps!
